'use strict';
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
let boot, data, current=0, episode='', tab='compare', pool=[], dirty=false, selected=-1, boxes=[], revision=0, timer=null, loadSerial=0, trainData;
const colors=['#c4f580','#ffb86b','#af8fff','#e9a4fa','#79dcff','#f1d876','#ffa6ae','#78ebbd','#cba3ff','#ffb86b','#df90b8','#76d5e8','#87b8ff','#d8b895','#d4ec85'];
function toast(s){$('toast').textContent=s;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,3000)}
function error(e){$('error').textContent=e.message||String(e);$('error').hidden=false;console.error(e)}
async function api(url,opts){const r=await fetch(url,opts),j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j}
function el(tag,attrs={},text){const n=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text!==undefined)n.textContent=text;return n}
function html(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function time(s){return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function mark(){dirty=true;$('dirty').textContent='Unsaved';$('applyOriginal').disabled=true;}
function abandon(){return !dirty||confirm('Discard unsaved box edits on this frame?')}
function stop(){clearInterval(timer);timer=null;$('play').textContent='▶ Play'}
function bound(){return $('view').value==='crop'?boot.roi:[0,0,1920,1080]}
function clip(b,r){const [x,y,X,Y]=b.bbox_xyxy;const v=[Math.max(x,r[0]),Math.max(y,r[1]),Math.min(X,r[2]),Math.min(Y,r[3])];return v[2]>v[0]&&v[3]>v[1]?{...b,bbox_xyxy:v}:null}
function visible(items){const conf=Number($('confidence').value),c=$('classFilter').value;return items.filter(b=>(b.score??1)>=conf&&(c==='all'||b.class_id===Number(c))).map(b=>clip(b,bound())).filter(Boolean)}
function baseSVG(container){const r=bound(),svg=el('svg',{viewBox:`${r[0]} ${r[1]} ${r[2]-r[0]} ${r[3]-r[1]}`,role:'img','aria-label':'Frame with object annotation boxes',width:r[2]-r[0],height:r[3]-r[1]});const clipId=container.id+'-clip';svg.dataset.clip=clipId;const defs=el('defs'),cp=el('clipPath',{id:clipId});cp.append(el('rect',{x:r[0],y:r[1],width:r[2]-r[0],height:r[3]-r[1]}));defs.append(cp);svg.append(defs);svg.append(el('image',{href:`/image?id=${current}`,x:0,y:0,width:1920,height:1080,'clip-path':`url(#${clipId})`}));if($('view').value==='full'){const [x,y,X,Y]=boot.roi;svg.append(el('rect',{x,y,width:X-x,height:Y-y,fill:'none',stroke:'#ffffff99','stroke-width':3,'stroke-dasharray':'12 8','pointer-events':'none'}))}container.replaceChildren(svg);return svg}
function drawBox(svg,b,i,editing=false){const [x,y,X,Y]=b.bbox_xyxy,c=colors[b.class_id],scale=$('view').value==='crop'?1:1.9;
 const g=el('g',{'data-box':i,'clip-path':`url(#${svg.dataset.clip})`});g.append(el('rect',{x,y,width:X-x,height:Y-y,fill:editing&&selected===i?`${c}25`:'transparent',stroke:c,'stroke-width':editing&&selected===i?4:2.5,'vector-effect':'non-scaling-stroke'}));
 const name=boot.classes[b.class_id].name+(typeof b.score==='number'?` ${b.score.toFixed(2)}`:'');const font=13*scale,top=Math.max(bound()[1],y-font-7);g.append(el('rect',{x,y:top,width:Math.min(name.length*font*.58+10,bound()[2]-x),height:font+7,fill:c,'pointer-events':'none'}));g.append(el('text',{x:x+4,y:top+font+1,fill:'#0a1717','font-size':font,'font-family':'Segoe UI,sans-serif','pointer-events':'none'},name));
 if(editing&&selected===i){[[x,y],[X,y],[X,Y],[x,Y]].forEach(([cx,cy],corner)=>g.append(el('rect',{x:cx-6*scale,y:cy-6*scale,width:12*scale,height:12*scale,fill:'#fff',stroke:c,'stroke-width':2,'data-corner':corner})))}svg.append(g)}
function maskURL(seg,color){
 // COCO compressed RLE: signed 5-bit integers with a two-run delta, column-major pixels.
 let counts=[],p=0;const s=seg.counts;
 if(Array.isArray(s))counts=s;else while(p<s.length){let x=0,k=0,c;do{c=s.charCodeAt(p++)-48;x|=(c&31)<<(5*k++);}while(c&32);if(c&16)x|=(-1)<<(5*k);if(counts.length>2)x+=counts[counts.length-2];counts.push(x)}
 const [h,w]=seg.size,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d'),im=ctx.createImageData(w,h),rgb=color.match(/\w\w/g).map(x=>parseInt(x,16));let pos=0;
 counts.forEach((n,i)=>{if(i%2)for(let j=pos;j<pos+n;j++){const off=((j%h)*w+Math.floor(j/h))*4;im.data[off]=rgb[0];im.data[off+1]=rgb[1];im.data[off+2]=rgb[2];im.data[off+3]=85}pos+=n});ctx.putImageData(im,0,0);return canvas.toDataURL();
}
function compare(){if(!data)return;const a=baseSVG($('samCanvas')),b=baseSVG($('yoloCanvas')),sam=visible(data.sam),yolo=visible(data?.yolo?.boxes||[]);if($('maskToggle').checked)sam.forEach(x=>{if(x.segmentation){if(!x.segmentation._url)x.segmentation._url=maskURL(x.segmentation,colors[x.class_id]);a.append(el('image',{href:x.segmentation._url,x:0,y:0,width:1920,height:1080,'pointer-events':'none','clip-path':`url(#${a.dataset.clip})`}))}});sam.forEach((x,i)=>drawBox(a,x,i));yolo.forEach((x,i)=>drawBox(b,x,i));$('samCount').textContent=`${sam.length} visible`;$('yoloCount').textContent=data.yolo?`${yolo.length} visible`:'Prediction not cached yet';}
function sourceBoxes(){const r=$('scope').value==='crop'?boot.roi:[0,0,1920,1080];return data.sam.map(b=>clip(b,r)).filter(Boolean).map(b=>({class_id:b.class_id,bbox_xyxy:[...b.bbox_xyxy]}))}
function renderEditor(){if(!data)return;$('applyOriginal').disabled=dirty||data.review?.status!=='approved';$('previewSource').textContent=data.review?'Saved review labels':'Current dataset labels (all classes in scope)';const svg=baseSVG($('editCanvas'));boxes.forEach((b,i)=>drawBox(svg,b,i,true));svg.addEventListener('pointerdown',pointerDown);$('boxList').replaceChildren();boxes.forEach((b,i)=>{const btn=html('button','box-row'+(i===selected?' selected':''));btn.append(html('span','',`${i+1}. ${boot.classes[b.class_id].name}`),html('span','',b.bbox_xyxy.map(Math.round).join(', ')));btn.onclick=()=>{selected=i;$('editClass').value=b.class_id;renderEditor()};$('boxList').append(btn)});$('deleteBox').disabled=selected<0;$('fromTraining').disabled=!data.training;$('fromYolo').disabled=!data.yolo;}
function pointerDown(e){if(e.button!==0)return;e.preventDefault();stop();const svg=e.currentTarget,pt=()=>{const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())};const r=$('scope').value==='crop'?boot.roi:[0,0,1920,1080],p=pt();p.x=Math.max(r[0],Math.min(r[2],p.x));p.y=Math.max(r[1],Math.min(r[3],p.y));const hit=e.target.closest('[data-box]'),corner=e.target.getAttribute('data-corner');let idx=hit?Number(hit.getAttribute('data-box')):-1;const original=idx>=0?[...boxes[idx].bbox_xyxy]:null,start={x:p.x,y:p.y};let changed=false;
 if(idx>=0){selected=idx;$('editClass').value=boxes[idx].class_id}else{idx=boxes.length;selected=idx;boxes.push({class_id:Number($('editClass').value),bbox_xyxy:[p.x,p.y,p.x,p.y]})}
 svg.setPointerCapture(e.pointerId);
 function move(ev){const q=svg.createSVGPoint();q.x=ev.clientX;q.y=ev.clientY;const t=q.matrixTransform(svg.getScreenCTM().inverse());const x=Math.max(r[0],Math.min(r[2],t.x)),y=Math.max(r[1],Math.min(r[3],t.y));let v;
 if(!original)v=[Math.min(start.x,x),Math.min(start.y,y),Math.max(start.x,x),Math.max(start.y,y)];else if(corner!==null){v=[...original];const c=Number(corner);v[c===0||c===3?0:2]=x;v[c<2?1:3]=y;v=[Math.min(v[0],v[2]),Math.min(v[1],v[3]),Math.max(v[0],v[2]),Math.max(v[1],v[3])]}else{const dx=Math.max(r[0]-original[0],Math.min(r[2]-original[2],x-start.x)),dy=Math.max(r[1]-original[1],Math.min(r[3]-original[3],y-start.y));v=[original[0]+dx,original[1]+dy,original[2]+dx,original[3]+dy]}
 boxes[idx].bbox_xyxy=v;changed=true;const old=svg.querySelector(`[data-box="${idx}"]`);old?.remove();drawBox(svg,boxes[idx],idx,true);
 }
 function end(){svg.removeEventListener('pointermove',move);svg.removeEventListener('pointerup',end);svg.removeEventListener('pointercancel',end);const v=boxes[idx].bbox_xyxy;if(v[2]-v[0]<2||v[3]-v[1]<2){if(!original){boxes.splice(idx,1);selected=-1}else boxes[idx].bbox_xyxy=original;}else if(changed)mark();renderEditor();}
 svg.addEventListener('pointermove',move);svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);
}
function setPool(){const filter=$('frameFilter').value;pool=boot.frames.filter(f=>f.source_video===episode&&(filter==='all'||filter==='training'&&f.training||filter==='unused'&&!f.training||filter===f.status));$('frameSlider').max=Math.max(0,pool.length-1);}
function filmstrip(){const pos=pool.findIndex(f=>f.id===current);$('frameSlider').value=Math.max(0,pos);$('position').textContent=`${pos+1} / ${pool.length}`;$('prev').disabled=pos<=0;$('next').disabled=pos>=pool.length-1;$('filmstrip').replaceChildren();pool.slice(Math.max(0,pos-3),Math.max(0,pos-3)+7).forEach(f=>{const btn=html('button',f.id===current?'current':'');const im=html('img');im.src=`/thumb?id=${f.id}`;im.alt=`Frame at ${time(f.timestamp_seconds)}`;btn.append(im,html('span','',`${time(f.timestamp_seconds)}${f.training?' · TRAIN':''}`));btn.onclick=()=>load(f.id);$('filmstrip').append(btn)});}
function renderVideos(){const videos=[...new Set(boot.frames.map(f=>f.source_video))];$('videoCount').textContent=videos.length;$('videos').replaceChildren();videos.forEach((v,i)=>{const btn=html('button','video'+(episode===v?' selected':''));btn.append(html('span','num',String(i+1).padStart(2,'0')),html('span','',v.replace(/^\d+_/,'').replace('.mp4','').replaceAll('-',' ')),html('small','',boot.frames.filter(f=>f.source_video===v).length));btn.onclick=()=>{if(!abandon())return;dirty=false;if(tab==='training')switchTab('compare');episode=v;setPool();if(!pool.length){$('frameFilter').value='all';setPool()}load(pool[0].id,true);renderVideos()};$('videos').append(btn)});const reviewed=boot.frames.filter(f=>f.status!=='pending').length;$('reviewProgress').textContent=`${reviewed} / ${boot.frames.length} frames reviewed`;}
async function load(id,force=false){if(!force&&!abandon())return;const serial=++loadSerial;dirty=false;selected=-1;current=id;data=null;$('dirty').textContent='';$('error').hidden=true;$('samCount').textContent='Loading…';$('yoloCount').textContent='Loading…';$('samCanvas').replaceChildren();$('yoloCanvas').replaceChildren();$('editCanvas').replaceChildren();$('saveReview').disabled=true;$('applyOriginal').disabled=true;try{const result=await api(`/api/frame?id=${id}`);if(serial!==loadSerial)return;data=result;const f=boot.frames[id];episode=f.source_video;setPool();renderVideos();$('episodeTitle').textContent=f.source_video.replace(/^\d+_/,'').replace('.mp4','').replaceAll('-',' ');$('frameMeta').textContent=`${time(f.timestamp_seconds)} · source frame ${f.frame_index} · 1920 × 1080 · ${f.training?'IN TRAINING SET':'NOT USED IN TRAINING — SAME SESSION'}`;$('reviewBadge').textContent=f.status.replace('_',' ').toUpperCase();boxes=structuredClone(data.review?.boxes||[]);revision=data.review?.revision||0;$('note').value=data.review?.note||'';$('decision').value=data.review?.status||'draft';$('scope').value=data.review?.scope||$('view').value;if(!data.review)boxes=sourceBoxes();$('saveReview').disabled=false;compare();renderEditor();filmstrip();}catch(e){stop();error(e)}}
function step(n){const p=pool.findIndex(f=>f.id===current),f=pool[p+n];if(f)load(f.id);else stop()}
function replaceBoxes(source){if(!data)return;if(dirty&&!confirm('Replace unsaved boxes with this source?'))return;const r=$('scope').value==='crop'?boot.roi:[0,0,1920,1080];boxes=source.map(b=>clip(b,r)).filter(Boolean).map(b=>({class_id:b.class_id,bbox_xyxy:[...b.bbox_xyxy]}));selected=-1;mark();renderEditor()}
async function save(){if(!data||$('saveReview').disabled)return;stop();$('saveReview').disabled=true;
 const id=current,serial=loadSerial,payload={frame:id,revision,status:$('decision').value,scope:$('scope').value,boxes:structuredClone(boxes),note:$('note').value};
 try{const record=await api('/api/review',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':boot.token},body:JSON.stringify(payload)});
 boot.frames[id].status=record.status;
 if(serial===loadSerial){data.review=record;revision=record.revision;const unchanged=JSON.stringify(boxes)===JSON.stringify(payload.boxes)&&$('note').value===payload.note&&$('decision').value===payload.status&&$('scope').value===payload.scope;if(unchanged){dirty=false;$('dirty').textContent='Saved'}$('reviewBadge').textContent=record.status.replace('_',' ').toUpperCase()}
 renderVideos();renderEditor();toast(`Saved revision ${record.revision}`);
 }catch(e){error(e)}finally{if(serial===loadSerial)$('saveReview').disabled=false}}

async function applyOriginal(){
 if(!data||dirty||data.review?.status!=='approved')return;
 stop();const id=current,serial=loadSerial;
 if(!confirm('Replace original dataset labels for this frame within the approved scope? Removed boxes in that scope will be deleted. Unchanged boxes retain their original masks; resized/new boxes have no mask. A backup will be kept.'))return;
 $('applyOriginal').disabled=true;
 try{const result=await api('/api/apply-original',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':boot.token},body:JSON.stringify({frame:id,revision,source_hash:data.source_hash})});
 if(serial===loadSerial&&!dirty)await load(id,true);
 toast('Original labels replaced. Backup saved.');
 }catch(e){error(e)}finally{if(serial===loadSerial&&data)renderEditor()}
}

async function switchTab(value){if(value!=='edit'&&dirty&&!abandon())return;if(value!=='edit'&&dirty){dirty=false;await load(current,true)}stop();tab=value;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===value));$('reviewView').hidden=value==='training';$('trainingView').hidden=value!=='training';$('compareView').hidden=value!=='compare';$('editView').hidden=value!=='edit';if(value==='training'&&!trainData){try{trainData=await api('/api/training');renderTraining()}catch(e){error(e)}}if(value==='edit')renderEditor();}
function chart(){const rows=trainData.rows,key=$('lossMetric').value,values=rows.map(r=>r[key]),max=Math.max(...values)*1.1;const svg=el('svg',{viewBox:'0 0 600 235',role:'img','aria-label':`${key} over 60 epochs`});for(let i=0;i<5;i++){const y=20+i*43;svg.append(el('line',{x1:45,x2:585,y1:y,y2:y,stroke:'#334044'}),el('text',{x:3,y:y+4,fill:'#9aabae','font-size':10},(max*(1-i/4)).toFixed(2)))}svg.append(el('polyline',{points:values.map((v,i)=>`${45+i/(values.length-1)*540},${192-v/max*172}`).join(' '),fill:'none',stroke:'#c4f580','stroke-width':2}));[1,15,30,45,60].forEach(n=>svg.append(el('text',{x:45+(n-1)/59*540,y:222,fill:'#9aabae','font-size':10},n)));$('lossChart').replaceChildren(svg)}
function renderTraining(){const d=trainData;$('stats').replaceChildren();[[d.rows.length,'epochs completed'],[d.frames.length,'training crops'],[d.counts.reduce((a,b)=>a+b,0),'corrected boxes'],['0','independent test sessions']].forEach(([v,label])=>{const x=html('div','stat');x.append(html('strong','',v),html('span','',label));$('stats').append(x)});chart();$('coverage').replaceChildren();d.counts.forEach((n,i)=>{const row=html('div','coverage-row'+(!n?' unsupported':'')),bar=html('div','bar'),fill=html('i');fill.style.width=`${n/Math.max(...d.counts)*100}%`;bar.append(fill);row.append(html('span','',boot.classes[i].name),bar,html('span','',n));$('coverage').append(row)});$('trainConfig').textContent=d.config;$('trainLog').textContent=d.log;$('trainingSamples').replaceChildren();d.frames.forEach(id=>{const f=boot.frames[id],btn=html('button'),im=html('img');im.loading='lazy';im.src=`/thumb?id=${id}`;im.alt=`Training sample ${id}`;btn.append(im,html('span','',`${f.source_video.slice(0,3)} · ${time(f.timestamp_seconds)}`));btn.onclick=async()=>{if(!abandon())return;dirty=false;$('frameFilter').value='all';await load(id,true);await switchTab('edit');$('scope').value='crop';$('view').value='crop';replaceBoxes(trainingBoxes());toast('Original training labels loaded as an unsaved draft')};$('trainingSamples').append(btn)})}
function trainingBoxes(){return (data?.training?.labels||[]).map(([class_id,x,y,X,Y])=>({class_id,bbox_xyxy:[x+500,y+330,X+500,Y+330]}))}
async function poll(){try{const s=await api('/api/status');$('cacheState').textContent=`YOLO cache: ${s.done.toLocaleString()} / ${s.total.toLocaleString()} · ${s.state}`;if(data&&!data.yolo&&s.done>current&&!dirty)await load(current,true);if(s.state==='failed')error(Error(s.error));}catch(e){$('cacheState').textContent='Connection lost — refresh when host is available'} }
async function init(){boot=await api('/api/bootstrap');boot.classes.forEach(c=>{for(const id of ['classFilter','editClass']){const opt=html('option','',c.name);opt.value=c.id;$(id).append(opt)}});episode=boot.frames[0].source_video;setPool();renderVideos();const requested=Number(new URLSearchParams(location.search).get('frame')||0);await load(Number.isInteger(requested)&&requested>=0&&requested<boot.frames.length?requested:0,true);
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('prev').onclick=()=>{stop();step(-1)};$('next').onclick=()=>{stop();step(1)};$('frameSlider').onchange=()=>{stop();load(pool[Number($('frameSlider').value)].id)};$('frameFilter').onchange=()=>{stop();if(!abandon()){$('frameFilter').value='all';return}setPool();if(pool.length)load(pool[0].id,true);else{toast('No matching frames in this episode');$('frameFilter').value='all';setPool();filmstrip()}};
 $('view').onchange=()=>{compare();renderEditor()};$('classFilter').onchange=compare;$('maskToggle').onchange=compare;$('confidence').oninput=()=>{$('confidenceValue').textContent=Number($('confidence').value).toFixed(2);compare()};$('play').onclick=()=>{if(timer){stop();return}if(dirty){toast('Save edits before playing');return}timer=setInterval(()=>{if(data)step(1)},900);$('play').textContent='Ⅱ Pause'};$('jumpGo').onclick=()=>{stop();const s=Number($('jump').value);if(pool.length)load(pool.reduce((a,b)=>Math.abs(a.timestamp_seconds-s)<Math.abs(b.timestamp_seconds-s)?a:b).id)};
 $('fromSam').onclick=()=>{if(data)replaceBoxes(visible(data.sam))};$('fromYolo').onclick=()=>replaceBoxes(visible(data?.yolo?.boxes||[]));$('fromTraining').onclick=()=>replaceBoxes(trainingBoxes());$('clearBoxes').onclick=()=>{if(boxes.length&&!confirm('Clear every box in this draft?'))return;boxes=[];selected=-1;mark();renderEditor()};$('deleteBox').onclick=()=>{if(selected<0)return;boxes.splice(selected,1);selected=-1;mark();renderEditor()};$('editClass').onchange=()=>{if(selected>=0){boxes[selected].class_id=Number($('editClass').value);mark();renderEditor()}};$('scope').onchange=()=>{if(!dirty&&!data.review)boxes=sourceBoxes();if($('scope').value==='crop')boxes=boxes.map(b=>clip(b,boot.roi)).filter(Boolean);$('view').value=$('scope').value;selected=-1;mark();compare();renderEditor()};$('note').oninput=mark;$('decision').onchange=mark;$('saveReview').onclick=save;$('applyOriginal').onclick=applyOriginal;$('lossMetric').onchange=chart;
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();if(tab==='edit')save();return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||tab==='training')return;if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.code==='Space'){e.preventDefault();$('play').click()}if(e.key==='Delete'&&tab==='edit')$('deleteBox').click()});await poll();setInterval(poll,5000);
}
init().catch(error);
